### PR TITLE
add compact unicode aliases

### PR DESCRIPTION
**Pull request by aminnj**
Add ΔR, Δϕ, Δη aliases

@Moelf 
@sgnoohc

### CODE REVIEW

**Comment by Moelf** [comment]
I'm for it, maybe we can show user how to figure out what to type:
```julia
help?> Δϕ
"Δϕ" can be typed by \Delta<tab>\phi<tab>
```

since this might be their early contact with Julia.

**Comment by Moelf** [comment]
really evil thing would be to just use Unicode for actual fields:
https://github.com/JuliaStats/Distributions.jl/blob/2856bc3e106d751a02e3fe9cccb046916a52955e/src/univariate/continuous/normal.jl#L31-L32

but knowing physicists, I say let's not do that.

**Comment by aminnj** [comment]
It seems this is already built into julia?
```
help?> Δϕ
"Δϕ" can be typed by \Delta<tab>\phi<tab>
```

**Comment by Moelf** [comment]
right, I'm saying let's put that into README too, so users don't get scared.

**Comment by aminnj** [comment]
done

**Pull request merged**
